spring.application.name=todo_list
spring.datasource.url=jdbc:h2:mem:todo
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.h2.console.path=/h2-console
spring.h2.console.enabled=true
spring.datasource.password=
spring.datasource.username=sa
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create

